# clamd.conf
PidFile /var/run/clamav/clamd.pid
DatabaseDirectory /var/lib/clamav
TCPSocket 3310
TCPAddr 0.0.0.0
User root
Foreground yes
AlgorithmicDetection yes
ScanArchive true
ScanPDF yes
LogFile /tmp/clamd.log
LogFileMaxSize 10M

MaxScanSize 250M
MaxFileSize 50M
MaxFiles 25000
MaxRecursion 10

# same as maxsize in squidclamav.conf
StreamMaxLength 10M
