#!/usr/bin/env python3
"""pages.yml bootstrap: render docs/board-snapshot.qmd from the GitHub Project
board (issues auto-link to it), so the site's plan-of-record is regenerated at
render time instead of hand-maintained. The board stays the single source; this
script is read-only against it."""
import datetime
import json
import os
import urllib.request
from collections import defaultdict

TOKEN = os.environ["GITHUB_TOKEN"]
OWNER = "shsingh"
PID = "PVT_kwHOAAZMgM4BlRK-"
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

H = {"Authorization": f"bearer {TOKEN}", "Content-Type": "application/json",
     "User-Agent": "shsingh"}

QUERY = """query($p:ID!,$a:String){
  node(id:$p){ ... on ProjectV2 {
    items(first:50, after:$a){
      pageInfo{ hasNextPage endCursor }
      nodes{
        content{ ... on Issue { number title url state } }
        fieldValues(first:15){ nodes{ __typename
          ... on ProjectV2ItemFieldSingleSelectValue { name
            field { ... on ProjectV2FieldCommon { name } } } }
        }
      }
    }
  }}
}"""


def gql(query, variables=None):
    req = urllib.request.Request("https://api.github.com/graphql",
        data=json.dumps({"query": query, "variables": variables or {}}).encode(),
        headers=H)
    with urllib.request.urlopen(req) as r:
        d = json.loads(r.read())
    if d.get("errors"):
        raise RuntimeError(json.dumps(d["errors"])[:300])
    return d["data"]


def collect():
    items, cursor = [], None
    while True:
        d = gql(QUERY, {"p": PID, "a": cursor})["node"]["items"]
        for n in d["nodes"]:
            c = n["content"]
            if not c or c["state"] != "OPEN":
                continue
            vals = {}
            for fv in n["fieldValues"]["nodes"]:
                if fv.get("__typename") == "ProjectV2ItemFieldSingleSelectValue":
                    fname = (fv.get("field") or {}).get("name")
                    if fname:
                        vals[fname] = fv["name"]
            items.append({"number": c["number"], "title": c["title"],
                          "url": c["url"], "area": vals.get("Area", ""),
                          "target": vals.get("Target", "")})
        if not d["pageInfo"]["hasNextPage"]:
            break
        cursor = d["pageInfo"]["endCursor"]
    return items


def main():
    items = collect()
    by_target = defaultdict(list)
    for i in items:
        by_target[i["target"] or "unassigned"].append(i)

    lines = [
        "<!-- AUTO-GENERATED by tests/build_board_snapshot.py - do not edit.",
        "     Regenerated at render time (pages.yml). Source of truth: the board. -->",
        "## Plan of record",
        "",
        f"_Scope for the next two releases, refreshed {datetime.date.today().isoformat()}."
        " The full listing, including later targets and parked directions, lives on the"
        " [OpenSASE Roadmap project board](https://github.com/users/shsingh/projects/5).",
        "",
    ]
    # ONE aligned table: Target | # | Item | Area — the next TWO non-empty
    # target groups; targets beyond that live on the board.
    order = ["v0.1.x", "v0.2.x", "Later"]
    groups = []
    for tgt in order:
        if by_target.get(tgt):
            groups.append(tgt)
        if len(groups) == 2:
            break
    lines += ["", "| Target | # | Item | Area |", "|--------|---|------|------|"]
    for tgt in groups:
        for i in sorted(by_target[tgt], key=lambda x: x["number"]):
            title = i["title"].replace("|", "\\|")
            area = i["area"] or "—"
            lines.append(f"| **{tgt}** | [#{i['number']}]({i['url']}) | {title} | {area} |")
    lines.append("")

    out = os.path.join(REPO_ROOT, "docs", "_board-snapshot.qmd")
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"board snapshot: {len(items)} open items -> {out}")


if __name__ == "__main__":
    main()
