name: pages
on:
  push:
    branches: [master]
    paths:
      - '_quarto.yml'
      - 'docs/**'
      - 'index.qmd'
      - 'README.md'
      - 'assets/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-26.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@91dabb203fce7f899d10ef8e482d94b00f397cbc # main@2026-06-17

      - name: Render site
        run: quarto render

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@98ef48e41587a300b82de4cf298aa98b57b2faae # main@2026-06-04
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-26.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5.0.1